name: keyword_release_test

on: push

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v2
        - uses: ./actions/releaser
          env: 
                GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          with:
            args: 'FIXED'
